name: Update Wait Times

# Tells GitHub when to run the script
on:
  schedule:
    # Runs every XX minutes automatically
    - cron: '*/30 * * * *'
  # Allows you to manually click a "Run" button in the GitHub UI
  workflow_dispatch: 

permissions:
  # Required to allow the bot to save the data.json file back to the repository
  contents: write 

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the entire history.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data.json
          
          # Exit silently if the data hasn't actually changed
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # Get the exact commit message of the last commit
          LAST_MESSAGE=$(git log -1 --pretty=format:'%s')
          
          echo "Last commit message was: '$LAST_MESSAGE'"

          # Check if the last commit was our automated message
          if [ "$LAST_MESSAGE" = "Auto-update live wait times" ]; then
            echo "Bot made the last commit. Amending..."
            git commit --amend -m "Auto-update live wait times"
            git push --force
          else
            echo "Human made the last commit. Creating a new one..."
            git commit -m "Auto-update live wait times"
            git push
          fi